version: '3'
services:
    prerender:
        image: tvanro/prerender-alpine:6.0.1
        ports:
        - 3000:3000
        environment:
        - WITH_CACHE='yes'
        - CACHE_MAXSIZE=1000
        - CACHE_TTL=6000
        restart: unless-stopped